packages/hardhat-resolc/src/compile/binary.ts
packages/hardhat-resolc/src/compile/index.ts
packages/hardhat-resolc/src/types.ts
packages/hardhat-resolc/src/utils.ts

This adds a config option for the binary compiler to compile the files in batches, useful for compilation in environments with limited resources and projects with a large number of contracts to compile.

feat(hardhat-resolc): Enable batch compilation

---

packages/hardhat-resolc/README.md
packages/hardhat-resolc/src/type-extensions.ts
packages/hardhat-revive-node/README.md
packages/hardhat-revive-node/src/type-extensions.ts

Updated `type-extensions` to make some values optional, to avoid forcing the user to define "polkavm" and allow it to be undefined.

fix(bug): Updated types

---

packages/hardhat-resolc/src/index.ts
packages/hardhat-resolc/src/type-extensions.ts
packages/hardhat-revive-node/src/index.ts

`ignition` was looking for artifacts that weren't there, and therefore causing the deployment to fail. Now we have updated the artifacts removal in `hardhat-resolc` to correct this.
Start a new hardhat ts project:
```bash
npx hardhat init
```
Update the `hardhat.config.ts` file as follows:
```ts
import "@nomicfoundation/hardhat-network-helpers";
import "@nomicfoundation/hardhat-chai-matchers";
import "@nomicfoundation/hardhat-ethers";
import "hardhat-gas-reporter";
import '@nomicfoundation/hardhat-ignition';
import <path-to-hardhat-resolc>;
import <path-to-hardhat-node>;
import { HardhatUserConfig } from "hardhat/config";
const config: HardhatUserConfig = {
solidity: "0.8.28",
resolc: {
compilerSource: 'binary',
settings: {
optimizer: {
enabled: true,
runs: 400,
},
evmVersion: "istanbul", …
```

fix(hardhat ignition): Fix artifact handling in ignitiion

---

packages/hardhat-resolc/src/index.ts

This changes the bytecode format to have a hex prefix to match the regular hardhat artifact's format.
Rel: https://github.com/paritytech/contract-issues/issues/25

fix(hardhat-ignition): updated bytecode format to match ignition's

---

packages/hardhat-revive-node/README.md
packages/hardhat-revive-node/src/utils.ts

This changes the behavior of the chainId setup. It now retrieves the `chainId` retrieved from the chain instead of the one defined in the `hardhat.config`, in order to avoid this error:
```bash
HardhatError: HH101: Hardhat was set to use chain id 31337, but connected to a chain with id 420420421.
```
Closes #31

fix(hardhat-node): retrieve chainId from chain

---

packages/hardhat-resolc/src/compile/binary.ts
packages/hardhat-resolc/src/compile/npm.ts
packages/hardhat-resolc/src/utils.ts

This adds a warning when using the property `batchSize`. This is a stopgap solution until we have a more definite solution for using the `batchSize` option with relative imports.
cc: @BigTava 
Rel: #23

fix(bug): fix relative imports

---

packages/hardhat-polkadot-node/src/utils.ts
packages/hardhat-polkadot/package.json
pnpm-lock.yaml
tests/run.sh

The `BuildBlockMode` command was not being parsed correctly du to the argument check being flawed.
Also reverted the umbrella `package.json` to use `workspace:^` again.

fix(hardhat-polkadot-node): chospticks commands are not parsed.

---

.github/dependabot.yaml

Tells dependabot to ignore `chalk` upgrades, since moving to `chalk@5.*.*` breaks our usage.

chore(dependabot): ignore chalk upgrades

---

package.json
packages/hardhat-polkadot-resolc/package.json
pnpm-lock.yaml
tests/fixture-projects/compile/package.json

Seeing that [6614](https://github.com/NomicFoundation/hardhat/issues/6614) was fixed by 2.24.0, we update hardhat's version to latest. At the same time, seeing that `@parity/resolc` [will handle the check for which `solc` version is compatible](https://github.com/paritytech/revive/blob/1b8fcc464908502de5ac2e5b0a20bcb383e5b27b/js/resolc/package.json#L35), we remove the overrides.

chore(deps): update deps

---

packages/hardhat-polkadot/recommended-gitignore.txt

fix(hardhat-polkadot): updated gitignore to contain *-pvm folders

---

packages/hardhat-polkadot/src/sizeCheckPatch.ts

This PR adds support for the `run` argument to the code size patch check in `sizeCheckPatch.ts`:
While npx hardhat test and npx hardhat ignition deploy correctly trigger the size check patch, running custom scripts (e.g., npx hardhat run scripts/deploy.js) does not. This results in [the original "initcode size too large" error](https://github.com/paritytech/contract-issues/issues/47) resurfacing when deploying contracts with large bytecode.
I encountered this issue when deploying Uniswap contracts with a custom deploy script ([example commit](https://github.com/papermoonio/uniswap-v2-polkadot/commit/fe03476f92cf30e36e634635e38845a8272e23ae#diff-c3527339cbf27248d3fa8d6d3f71a29f8394aac4a0b62d35R22-R25)):
```bash
Deploying UniswapV2Pair...
Error: the initcode size of this transaction is too …
```

fix(hardhat-polkadot): code size check when running custom scripts

---

packages/hardhat-polkadot-resolc/src/utils.ts

Small bug on how the compiler configuration was updated was preventing `hardhat` from recognizing cached artifacts.
Closes #124

fix(hardhat-resolc): avoid compiling cached artifacts

---

packages/hardhat-polkadot-node/src/index.ts
packages/hardhat-polkadot-node/src/servers/docker-server.ts
packages/hardhat-polkadot-node/src/utils.ts

This removes the check for node and adapter path to decide if we wait for the port to be ready or not.

fix(hardhat-polkadot-node): fix node not connecting

---

packages/hardhat-polkadot-node/src/core/global-interceptor.ts
packages/hardhat-polkadot-node/src/core/script-runner.ts
packages/hardhat-polkadot-node/src/index.ts
packages/hardhat-polkadot-node/src/servers/docker-server.ts
packages/hardhat-polkadot-node/src/servers/path-to-binaries-server.ts
packages/hardhat-polkadot-node/src/servers/utils.ts
packages/hardhat-polkadot-node/src/utils.ts

- Moves `waitForNodeToBeReady` to servers folder and splits into `waitForEthRpcToBeReady`. Previously `waitForNodeToBeReady(true)` was very confusing
- `npx hardhat test` multiple times works. The service was being launched on port 8545 but we were waiting for a response in port 8546
- reads the adapter port correctly
- replaces --port arg with --rpc-port since eth-rpc fails with --port arg

fix: restart node and eth-rpc

---

packages/hardhat-polkadot-node/src/index.ts

This enables setting up an env before testing, via `TASK_TEST_SETUP_TEST_ENVIRONMENT`.
Closes #195

fix(hardhat-polkadot-node): include setup task in test override

---

packages/hardhat-polkadot-resolc/src/compile/binary.ts
packages/hardhat-polkadot-resolc/src/compile/index.ts
packages/hardhat-polkadot-resolc/src/compile/npm.ts
packages/hardhat-polkadot-resolc/src/constants.ts
packages/hardhat-polkadot-resolc/src/index.ts
packages/hardhat-polkadot-resolc/src/types.ts
packages/hardhat-polkadot-resolc/src/utils.ts

This enables using multiple `solc` versions with the `binary` compiler. It still errors when trying to use with `npm` as the compiler source since handling multiple versions of the same dependency concurrently is incredibly complex.
Closes #176

fix(hardhat-polkadot-resolc): enable usage of multiple solidity versions.

---

examples/localNode.config.ts
packages/hardhat-polkadot-resolc/src/compile/binary.ts
packages/hardhat-polkadot-resolc/src/compile/index.ts
packages/hardhat-polkadot-resolc/src/index.ts
packages/hardhat-polkadot-resolc/src/types.ts
packages/hardhat-polkadot-resolc/src/utils.ts

Updates the comiler options and types to match the `standard-json` input defined in [`resolc`](https://github.com/paritytech/revive/blob/ed608699af7b7f8a329765ec69b10a7fd4eac604/crates/resolc/src/lib.rs#L211-L217)

fix(hardhat-polkadot-resolc): updated types

---

packages/hardhat-polkadot-resolc/src/utils.ts

This removes the check for the compiler source from the solidity version warning, since the restriction is applicable to the compiler, independent of whether it's the binary or the npm package.

fix(hardhat-polkadot-resolc): cleanup compiler version warning

---

packages/hardhat-polkadot-node/src/types.ts
packages/hardhat-polkadot-node/src/utils.ts

There's been a break in the `revive-dev-node` that's causing instant seal to not produce any blocks. This PR adds the option to define other types of consensus to work around this.
An example would be:
```ts
const config: HardhatUserConfig = {
solidity: "0.8.30",
networks: {
hardhat: {
polkavm: true,
nodeConfig: {
nodeBinaryPath: "path/to/substrate-node/binary",
rpcPort: 8000,
dev: true,
consensus: {
seal: "Manual",
period: 50,
},
adapterConfig: {
adapterBinaryPath: "path/to/eth-rpc-adapter",
dev: true,
},
},
},
resolc: {
compilerSource: "binary",
settings: {
optimizer: {
enabled: true,
},
compilerPath: "path/to/resolc",
},
},
}
```

fix(hardhat-polkadot-node): add consensus type to dev node options

---

packages/hardhat-polkadot-resolc/src/index.ts

Now without specifying the `compilerSource` inside of `resolc`, it defaults to the binary default configuration.

fix(hardhat-polkadot-resolc): fix resolc default

---

package.json
pnpm-lock.yaml

This resolves `micro-eth-signer` to 0.16.0 to keep the fix detailed [here](https://github.com/NomicFoundation/hardhat/issues/6950#issue-3189814970) that was then backtracked by hardhat.

fix(deps): resolve micro-eth-signer to 0.16.0

---

packages/hardhat-polkadot-node/src/constants.ts
packages/hardhat-polkadot-node/src/utils.ts

This renames the node to `anvil` so that it works with the hardhat network helpers. It also makes it pull the accounts from the node instead of using the local hardcoded ones.

fix(hardhat-polkadot-node): rename to work with network helpers

---

packages/hardhat-polkadot/.npmrc
packages/hardhat-polkadot/package.json
pnpm-lock.yaml

Both `npm` and `pnpm` behave buggy with these, skipping their
dependencies.
Then, because smart contract project will probably have some versions of
ethers or lru-cache, we're getting errors like these:
```
TypeError: lru_cache_1.LRUCache is not a constructor
```
As `@parity/hardhat-polkadot-node` and `@parity/hardhat-polkadot-resolc`
are in dependencies or `@parity/hardhat-polkadot`, they will be
installed automatically.
Do these serve the purpose of eased local development?

fix: removing `bundledDependencies`

---

packages/hardhat-polkadot-node/src/utils.ts

In order to have `snapshot`, `reset` and `revert` work with our node, we need it to be an archive node. This adds this flag when starting the node.

fix(hardhat-polkadot-node): spin up an archive node

---

.github/workflows/release-dev-node.yml

- Fixes checksums: i was still adding single OS checksum
- Adds latest source branch commit hash to a release details 
- Added a flag to skip making as latest (to release individual bundles without affecting the latest)
Test release: https://github.com/paritytech/hardhat-polkadot/releases/tag/nodes-17163658765

ci: Small change in dev-node release

---

packages/hardhat-polkadot-resolc/src/compile/npm.ts
pnpm-lock.yaml
tests/e2e/1-test-in-memory.test.sh
tests/e2e/2-deploy-in-node.test.sh
tests/unit/compile-basic.test.sh
tests/unit/compile-multiple.test.sh

This replaces the `npm ...` commando with `pnpm ...` since it was causing problems when installing `solc` for usage with `npm` as the source.
Closes #280 
Rel: https://github.com/paritytech/contract-issues/issues/144

fix(hardhat-polkadot): Replace npm references with pnpm 

---

.github/workflows/release-dev-node.yml

Removed x86_64-apple-darwin target from build matrix.

chore: Update build matrix in release-dev-node.yml
